require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task :default => :spec

require 'rake'
require 'rake/extensiontask'

Rake::ExtensionTask.new do |ext|
  ext.name = 'mlpack'
  ext.ext_dir = 'ext/mlpack/'
  ext.lib_dir = 'lib/'
  ext.source_pattern = '**/*.{c,cpp, h}'
end

task :console do
  cmd = ['irb', "-r './lib/mlpack.rb'"]
  run(*cmd)
end

task :pry do
  cmd = ['pry', "-r './lib/mlpack.rb'"]
  run(*cmd)
end

def run(*cmd)
  sh(cmd.join(' '))
end
